### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by HapLifeMan** [claytonrcarter/hyperclick-php#1]
Hello,

I can't see hyperlinks in PHP... Can you help me ?
Does it require something else to work... ?

Thanks!

**Comment by claytonrcarter** [comment]
Yes, it requires the Hyperclick package. Also, links only display when the alt or command key (depending on your system) is pressed.

**Comment by HapLifeMan** [comment]
Yes, I tested with Hyperclick but nothing too...

**Comment by claytonrcarter** [comment]
Sorry. You'll have to give me more information.  What scopes are showing up in your editor? What are you trying to click? Are there any relevant messages in the dev console?

**Comment by HapLifeMan** [comment]
I'm trying to click on this function: http://puu.sh/lY2EH/bd1d4dea63.png (cleanMe)...
There's nothing in the dev console an no scope...

**Comment by claytonrcarter** [comment]
Got it. As I said in the readme, it currently only works for variable definitions and "require" or "include" files. Functions aren't supported (linked) yet.

**Comment by claytonrcarter** [comment]
@HapLifeMan If you want to give this a second try, I just added basic support for functions.  They must be defined in the same file as being called. :confused:
