### ISSUE TITLE
Jumping to Classes not working on non-composer projects

### ISSUE THREAD

**Issue by jcchikikomori** [claytonrcarter/hyperclick-php#7]
I am currently using an older version of CakePHP which is 1.3
And i am not able to jump to any classes (user-defined or not)

**Comment by claytonrcarter** [comment]
Can you double check the README section of ["Known Issues"](https://github.com/claytonrcarter/hyperclick-php#known-issues) to make sure that this package is even trying to do what you want to do? I'm pretty sure that it will work for following variable definitions in and files brought in with `require`, but I never even tried to get it to work for class definitions. Have you looked into [`ide-php`](https://atom.io/packages/ide-php), I believe that that might offer what you're looking for.

**Comment by jcchikikomori** [comment]
I see it now. I just disabled other packages that conflicts (autocomplete, linter-php & integrator) and it's fixed. Although this could not guarantee the whole functionality based on Known Issues on README. Thanks for responding
